apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: obo-pdfgenrs
  namespace: obo
  labels:
    team: obo
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://obo-pdfgenrs.intern.dev.nav.no
  liveness:
    path: /internal/is_alive
  readiness:
    path: /internal/is_alive
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      memory: 768Mi
    requests:
      cpu: 15m
      memory: 512Mi
  accessPolicy:
    inbound:
      rules:
        - application: veilarbvedtaksstotte